Abriendo los repositorios:
C:\Users\Bertha\Documents\Git\PuntoVenta
Se creó la confirmación a0fe3fe0 localmente en el repositorio C:\Users\Bertha\Documents\Git\PuntoVenta
Error: failed to push some refs to 'https://github.com/AniBertha/PuntoVenta.git'
Error: hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Se produjo un error al insertar en el repositorio remoto: rejected Updates were rejected because the remote contains work that you do not have locally. This is usually caused by another repository pushing to the same ref. You may want to first integrate the remote changes before pushing again.
